replicaCount: 1

imagePullSecretsName: gitlab-registry-secret

serviceAccountCreate: true
serviceAccountAnnotations: {}
serviceAccountName: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

serviceType: NodePort
servicePort: 80

ingressEnabled: true
ingressClassName: ""
ingressAnnotations: {}
ingressHosts:
  - host: 10.195.70.44.nip.io
    paths:
      - path: /
        pathType: ImplementationSpecific
tls: []

autoscalingEnabled: true
autoscalingMinReplicas: 1
autoscalingMaxReplicas: 5
autoscalingTargetCPUUtilizationPercentage: 80
autoscalingTargetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}


resourcesRequests:
  cpu: "200m"
  memory: "128Mi"
ressourcesLimits:
  cpu: "500m"
  memory: "512Mi"

services:
  - name: frontend
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/frontend:latest
    port: 80
    nodePort: 30001

  - name: cartservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/cartservice:latest
    port: 80
    nodePort: 30002

  - name: productcatalogservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/productcatalogservice:latest
    port: 80
    nodePort: 30003

  - name: currencyservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/currencyservice:latest
    port: 80
    nodePort: 30004

  - name: paymentservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/paymentservice:latest
    port: 80
    nodePort: 30005

  - name: shippingservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/shippingservice:latest
    port: 80
    nodePort: 30006

  - name: emailservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/emailservice:latest
    port: 80
    nodePort: 30007

  - name: checkoutservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/checkoutservice:latest
    port: 80
    nodePort: 30008

  - name: recommendationservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/recommendationservice:latest
    port: 80
    nodePort: 30009

  - name: adservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/adservice:latest
    port: 80
    nodePort: 30010
