replicaCount: 1

image:
  repository: registry.gitlab.unige.ch/filipe.ramos/k8s-project
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: 
  - name: gitlab-registry-secret

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: 10.195.70.44.nip.io 
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

services:
  frontend:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/frontend:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30001

  cartservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/cartservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30002

  productcatalogservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/productcatalogservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30003

  currencyservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/currencyservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30004

  paymentservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/paymentservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30005

  shippingservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/shippingservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30006

  emailservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/emailservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30007

  checkoutservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/checkoutservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30008

  recommendationservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/recommendationservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30009

  adservice:
    create: true
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/adservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30010
