# Default values for onlineboutique.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: 
  - name: gitlab-registry-secret

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 80
  nodePort: 30000 

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: 10.195.70.44.nip.io 
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

services:
  frontend:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/frontend:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30001

  cartservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/cartservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30002

  productcatalogservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/productcatalogservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30003

  currencyservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/currencyservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30004

  paymentservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/paymentservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30005

  shippingservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/shippingservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30006

  emailservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/emailservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30007

  checkoutservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/checkoutservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30008

  recommendationservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/recommendationservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30009

  adservice:
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/adservice:latest
    args:
      - "--disable-profiler=true"
    service:
      type: NodePort
      port: 80
      nodePort: 30010
