replicaCount: 1

imagePullSecretsName: gitlab-registry-secret

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

serviceType: LoadBalancer
servicePort: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  ingressAnnotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60s"
  ingressHosts:
    - host: 10.195.70.44.nip.io
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

services:
  - name: frontend
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/frontend:latest
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:5050"
      - name: AD_SERVICE_ADDR
        value: "adservice:9555"
      - name: SHOPPING_ASSISTANT_SERVICE_ADDR
        value: "shoppingassistantservice:80"
  - name: cartservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/cartservice:latest
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
  - name: productcatalogservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/productcatalogservice:latest
    ports:
        - containerPort: 3550
    env:
      - name: EXTRA_LATENCY
        value: "5s"
      - name: PORT
        value: "3550"
  - name: currencyservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/currencyservice:latest
    ports:
      - name: grpc
        containerPort: 7000
    env:
      - name: PORT
        value: "7000"
      - name: GOOGLE_CLOUD_PROJECT
        value: "project-id"
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/etc/credentials/gcp-credentials.json"
      - name: MAIN_PROTO_PATH
        value: './proto/demo.proto'
      - name: HEALTH_PROTO_PATH
        value: './proto/grpc/health/v1/health.proto'
  - name: paymentservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/paymentservice:latest
    ports:
      - containerPort: 50051
    env:
      - name: PORT
        value: "50051"
      - name: GOOGLE_CLOUD_PROJECT
        value: "mon-project-id"
  - name: shippingservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/shippingservice:latest
    port: 80
    env:
      - name: APP_PORT
        value: "50051"
      - name: PORT
        value: 50051
  - name: emailservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/emailservice:latest
    port: 80
  - name: checkoutservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/checkoutservice:latest
    ports:
      - containerPort: 5050
    env:
      - name: PORT
        value: "5050"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice:50051"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice:5000"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
  - name: recommendationservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/recommendationservice:latest
    ports:
      - containerPort: 8080
      - name: grpc
        port: 8080
        targetPort: 8080
    env:
      - name: PORT
        value: "8080"
  - name: adservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/adservice:latest
    ports:
      - containerPort: 9555
    env:
    - name: PORT
      value: "9555"