replicaCount: 1

imagePullSecretsName: gitlab-registry-secret

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

serviceType: LoadBalancer
servicePort: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  ingressAnnotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60s"
  ingressHosts:
    - host: 10.195.70.44.nip.io
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

services:
  - name: frontend
    image: ghcr.io/lip1200/k8s_project/frontend:latest
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:5050"
      - name: AD_SERVICE_ADDR
        value: "adservice:9555"
    readinessProbe:
      httpGet:
        path: /_healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /_healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: cartservice
    image: ghcr.io/lip1200/k8s_project/cartservice:latest
    ports:
      - containerPort: 7070
    env:
      - name: ASPNETCORE_URLS
        value: "http://*:7070"
      - name: REDIS_ADDR
        value: "redis:6379"
    readinessProbe:
      tcpSocket:
        port: 7070
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 7070
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: productcatalogservice
    image: ghcr.io/lip1200/k8s_project/productcatalogservice:latest
    ports:
      - containerPort: 3550
    env:
      - name: EXTRA_LATENCY
        value: "5s"
      - name: PORT
        value: "3550"
    readinessProbe:
      tcpSocket:
        port: 3550
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 3550
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: currencyservice
    image: ghcr.io/lip1200/k8s_project/currencyservice:latest
    ports:
      - containerPort: 7000
    env:
      - name: PORT
        value: "7000"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      tcpSocket:
        port: 7000
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 7000
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: paymentservice
    image: ghcr.io/lip1200/k8s_project/paymentservice:latest
    ports:
      - containerPort: 50051
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      tcpSocket:
        port: 50051
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 50051
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: shippingservice
    image: ghcr.io/lip1200/k8s_project/shippingservice:latest
    ports:
      - containerPort: 50051
    env:
      - name: PORT
        value: "50051"
    readinessProbe:
      tcpSocket:
        port: 50051
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 50051
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: emailservice
    image: ghcr.io/lip1200/k8s_project/emailservice:latest
    ports:
      - containerPort: 5000
    env:
      - name: PORT
        value: "5000"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: checkoutservice
    image: ghcr.io/lip1200/k8s_project/checkoutservice:latest
    ports:
      - containerPort: 5050
    env:
      - name: PORT
        value: "5050"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice:50051"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice:5000"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
    readinessProbe:
      tcpSocket:
        port: 5050
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 5050
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: recommendationservice
    image: ghcr.io/lip1200/k8s_project/recommendationservice:latest
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 15
  - name: adservice
    image: ghcr.io/lip1200/k8s_project/adservice:latest
    ports:
      - containerPort: 9555
    env:
      - name: PORT
        value: "9555"
    readinessProbe:
      tcpSocket:
        port: 9555
      initialDelaySeconds: 20
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 9555
      initialDelaySeconds: 30
      periodSeconds: 15
