replicaCount: 1

imagePullSecretsName: gitlab-registry-secret

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

serviceType: LoadBalancer
servicePort: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  ingressAnnotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60s"
  ingressHosts:
    - host: 10.195.70.44.nip.io
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

services:
  - name: frontend
    type: LoadBalancer
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/frontend:latest
    port: 80
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: productcatalogservice:80
      - name: CURRENCY_SERVICE_ADDR
        value: currencyservice:80
      - name: CART_SERVICE_ADDR
        value: cartservice:80
      - name: RECOMMENDATION_SERVICE_ADDR
        value: recommendationservice:80
      - name: CHECKOUT_SERVICE_ADDR
        value: checkoutservice:80
      - name: SHOPPING_ASSISTANT_SERVICE_ADDR
        value: "shoppingassistantservice:8080"
      - name: AD_SERVICE_ADDR
        value: "adservice:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:8080"
    ports:
        - containerPort: 8080
  - name: cartservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/cartservice:latest
    port: 80
  - name: productcatalogservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/productcatalogservice:latest
    port: 80
    env:
      - name: EXTRA_LATENCY
        value: "5s"
  - name: currencyservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/currencyservice:latest
    port: 80
    env:
      - name: PORT
        value: "8080"
      - name: GOOGLE_CLOUD_PROJECT
        value: "project-id"
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/etc/credentials/gcp-credentials.json"
      - name: MAIN_PROTO_PATH
        value: './proto/demo.proto'
      - name: HEALTH_PROTO_PATH
        value: './proto/grpc/health/v1/health.proto'
      - name: PORT
        value: "8080"
  - name: paymentservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/paymentservice:latest
    port: 80
    env:
      - name: PORT
        value: "8080"
      - name: GOOGLE_CLOUD_PROJECT
        value: "your-project-id"
  - name: shippingservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/shippingservice:latest
    port: 80
  - name: emailservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/emailservice:latest
    port: 80
  - name: checkoutservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/checkoutservice:latest
    port: 80
    env:
      - name: SHIPPING_SERVICE_ADDR
        value: shippingservice:80
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: productcatalogservice:80
      - name: CURRENCY_SERVICE_ADDR
        value: currencyservice:80
      - name: CART_SERVICE_ADDR
        value: cartservice:80
      - name: EMAIL_SERVICE_ADDR
        value: emailservice:80
      - name: PAYMENT_SERVICE_ADDR
        value: paymentservice:80
      - name: RECOMMENDATION_SERVICE_ADDR
        value: recommendationservice:80
  - name: recommendationservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/recommendationservice:latest
    port: 80
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: productcatalogservice:80
  - name: adservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/adservice:latest
    port: 80
