replicaCount: 1

imagePullSecretsName: gitlab-registry-secret


podAnnotations: {}

podSecurityContext: {}
securityContext: {}

serviceType: LoadBalancer
servicePort: 80

ingress:
  enabled: true
ingressClassName: "nginx"
ingressAnnotations:
  nginx.ingress.kubernetes.io/rewrite-target: /$1
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/proxy-read-timeout: "60s"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "60s"
ingressHosts:
  - host: 10.195.70.44
    paths:
      - path: /
        pathType: Prefix
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

services:
  - name: frontend
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/frontend:latest
    port: 80

  - name: cartservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/cartservice:latest
    port: 80

  - name: productcatalogservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/productcatalogservice:latest
    port: 80

  - name: currencyservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/currencyservice:latest
    port: 80

  - name: paymentservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/paymentservice:latest
    port: 80

  - name: shippingservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/shippingservice:latest
    port: 80

  - name: emailservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/emailservice:latest
    port: 80

  - name: checkoutservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/checkoutservice:latest
    port: 80

  - name: recommendationservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/recommendationservice:latest
    port: 80

  - name: adservice
    image: registry.gitlab.unige.ch/filipe.ramos/k8s-project/adservice:latest
    port: 80
