{{- if .Values.networkPolicies.create }}
{{- range $service := .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $service.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- range $key, $value := $.Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if $.Values.ingressClassName }}
  ingressClassName: {{ $.Values.ingressClassName }}
  {{- end }}
  rules:
    {{- range $.Values.ingressHosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $service.name }}
                port:
                  number: 80
          {{- end }}
    {{- end }}
  {{- if $.Values.tls }}
{{- end }}
{{- end }}
{{- range $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  labels:
    app: {{ $service.name }}
    {{- include "onlineboutique.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
        {{- include "onlineboutique.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: "{{ $service.image }}"
          args:
            - "--disable-profiler=true"
          ports:
            - containerPort: 80
          env:
            {{- with $service.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecretsName }}
{{- end }}
