{{- if .Values.ingress.enabled }}
{{- range $service := .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $service.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- range $key, $value := $.Values.ingress.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  rules:
    - host: {{ $.Values.ingress.ingressHosts[0].host | quote }}
      http:
        paths:
          - path: /{{ $service.name }}
            pathType: {{ $.Values.ingress.ingressHosts[0].paths[0].pathType }}
            backend:
              service:
                name: {{ $service.name }}
                port:
                  number: 80
{{- end }}
---
{{- end }}
