{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onlineboutique-ingress
  namespace: onlineboutique
  annotations:
    {{- range $key, $value := .Values.ingress.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
    - host: {{ (index .Values.ingress.ingressHosts 0).host | quote }}
      http:
        paths:
          {{- range $service := .Values.services }}
          - path: {{ if eq $service.name "frontend" }}/{{ else }}/{{ $service.name }}{{ end }}
            pathType: Prefix
            backend:
              service:
                name: {{ $service.name }}
                port:
                  number: {{ $service.port }}
          {{- end }}
{{- end }}
