{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onlineboutique-ingress
  namespace: onlineboutique
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60s"
spec:
  ingressClassName: nginx
  rules:
    - host: 10.195.70.44.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /adservice
            pathType: Prefix
            backend:
              service:
                name: adservice
                port:
                  number: 80
          - path: /cartservice
            pathType: Prefix
            backend:
              service:
                name: cartservice
                port:
                  number: 80
          - path: /checkoutservice
            pathType: Prefix
            backend:
              service:
                name: checkoutservice
                port:
                  number: 80
          - path: /currencyservice
            pathType: Prefix
            backend:
              service:
                name: currencyservice
                port:
                  number: 80
          - path: /emailservice
            pathType: Prefix
            backend:
              service:
                name: emailservice
                port:
                  number: 80
          - path: /paymentservice
            pathType: Prefix
            backend:
              service:
                name: paymentservice
                port:
                  number: 80
          - path: /productcatalogservice
            pathType: Prefix
            backend:
              service:
                name: productcatalogservice
                port:
                  number: 80
          - path: /recommendationservice
            pathType: Prefix
            backend:
              service:
                name: recommendationservice
                port:
                  number: 80
          - path: /shippingservice
            pathType: Prefix
            backend:
              service:
                name: shippingservice
                port:
                  number: 80
{{- end }}
