{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- include "onlineboutique.labels" . | nindent 4 }}
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: 80
  selector:
    app: {{ $name }}
{{- end }}
