{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    {{- include "onlineboutique.labels" . | nindent 4 }}
spec:
  type: {{ $.Values.serviceType }}
  ports:
    - port: {{ $.Values.servicePort }}
      targetPort: 80
      nodePort: {{ .nodePort }}
  selector:
    app: {{ .name }}
{{- end }}
