{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
spec:
  type: {{ $.Values.serviceType }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
  selector:
    app: {{ $service.name }}
---
{{- end }}
