{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    app: {{ $service.name }}
    {{- include "onlineboutique.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: 80
  selector:
    app: {{ $service.name }}
---
{{- end }}
