{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: onlineboutique
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ $service.name }}
---
{{- end }}
